// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides AI-powered menu customization suggestions based on event details.
 *
 * - suggestMenuCustomization - A function that suggests menu customizations.
 * - SuggestMenuCustomizationInput - The input type for the suggestMenuCustomization function.
 * - SuggestMenuCustomizationOutput - The return type for the suggestMenuCustomization function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestMenuCustomizationInputSchema = z.object({
  eventType: z
    .string()
    .describe('The type of event (e.g., wedding, corporate, party).'),
  dietaryRestrictions: z
    .string()
    .describe(
      'Any dietary restrictions or preferences (e.g., vegetarian, vegan, gluten-free, allergies).'
    ),
  preferences: z
    .string()
    .describe('Specific food preferences or themes for the event.'),
  popularChoices: z
    .string()
    .describe('List of popular menu items or dishes.'),
});

export type SuggestMenuCustomizationInput = z.infer<
  typeof SuggestMenuCustomizationInputSchema
>;

const SuggestMenuCustomizationOutputSchema = z.object({
  menuSuggestions: z
    .string()
    .describe(
      'AI-powered menu customization suggestions based on the provided details.'
    ),
});

export type SuggestMenuCustomizationOutput = z.infer<
  typeof SuggestMenuCustomizationOutputSchema
>;

export async function suggestMenuCustomization(
  input: SuggestMenuCustomizationInput
): Promise<SuggestMenuCustomizationOutput> {
  return suggestMenuCustomizationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestMenuCustomizationPrompt',
  input: {schema: SuggestMenuCustomizationInputSchema},
  output: {schema: SuggestMenuCustomizationOutputSchema},
  prompt: `You are an expert catering consultant. Based on the event details, dietary restrictions, and preferences, provide creative and inspiring menu customization suggestions.

Event Type: {{{eventType}}}
Dietary Restrictions: {{{dietaryRestrictions}}}
Preferences: {{{preferences}}}
Popular Choices: {{{popularChoices}}}

Consider the event type, dietary restrictions, and preferences to create unique and personalized menu options. Provide detailed and creative suggestions. The output must be a string.
`,
});

const suggestMenuCustomizationFlow = ai.defineFlow(
  {
    name: 'suggestMenuCustomizationFlow',
    inputSchema: SuggestMenuCustomizationInputSchema,
    outputSchema: SuggestMenuCustomizationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
